In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

### 返回数组维度

In [4]:
print(arr1.ndim)
print(arr2.ndim)

1
2


### 返回数组各维度的元素个数

In [6]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


### 返回数组元素的总个数

In [8]:
print(arr1.size)
print(arr2.size)

3
6


### 返回数组元素的类型

In [9]:
print(arr1.dtype)

int64


In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.arange(5,9,0.2)

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8])

In [4]:
print("Aa?")

Aa?


In [2]:
print("Aa?")

Aa?


In [4]:
print("Aa?")

Aa?


# 

# 最大的标题

###### 小的

公式:
$$x^2 + y^2 = 1$$

In [16]:
arr3 = np.zeros(3)

In [21]:
arr4 = np.concatenate([arr1,arr3])

In [22]:
print(np.sort(arr4))

[0. 0. 0. 1. 2. 3.]


In [26]:
print(arr4[-6])

1.0


In [28]:
print(arr4[1:4])

[2. 3. 0.]


In [5]:
import pandas as pd

In [12]:
s1  = pd.Series([5,17,3,26,31],
         index=["a","d","b","c","e"])
s1

a     5
d    17
b     3
c    26
e    31
dtype: int64

In [13]:
s1.values

array([ 5, 17,  3, 26, 31])

In [14]:
s1.index

Index(['a', 'd', 'b', 'c', 'e'], dtype='object')

In [15]:
s1["b"]

np.int64(3)

In [16]:
s1[1:3]

d    17
b     3
dtype: int64

In [18]:
s1["d":"c"]

d    17
b     3
c    26
dtype: int64

In [21]:
s1[["a","e","c"]]

a     5
e    31
c    26
dtype: int64

In [23]:
s1.iloc[1:3]

d    17
b     3
dtype: int64